Repository QuantEcon/lecture-source-py, pull requests merged in 2018-11, with the labels that each got.

#115 edit tags in python_essentials.rst
  rst_files/python_essentials.rst
Labels: ready

#99 fix tags for 'intentional' errors : (python_advanced_features.rst)
  rst_files/python_advanced_features.rst
Labels: ready

#100 fix tags for 'intentional' errors : (python_by_example.rst)
  rst_files/python_by_example.rst
Labels: review

#111 fix tags for 'intentional' errors : (oop_intro.rst)
  rst_files/oop_intro.rst
Labels: review

#62 jit career.rst
  rst_files/career.rst
Labels: ready

#118 remove conda-forge discussion
  rst_files/getting_started.rst
Labels: ready

#63 jit optgrowth.rst
  rst_files/optgrowth.rst
Labels: ready

#64 jit perm_income.rst
  rst_files/perm_income.rst
Labels: ready

#66 jit lucas model
  rst_files/lucas_model.rst
Labels: ready

#109 [debugging] update execution tags for debugging lecture (special case)
  rst_files/debugging.rst
Labels: review

#127 replace \RR with \mathbb R
  rst_files/mccall_model.rst
  rst_files/orth_proj.rst
Labels: ready

#126 fix bolding in optgrowth.rst
  rst_files/optgrowth.rst
Labels: ready

#139 Add pdf badge, fix alignment #130 #113
  rst_files/_static/includes/lecture_howto_jl.raw
  rst_files/_static/includes/lecture_howto_py.raw
Labels: ready

#125 add url references for interdocument links and images for download no…
  rst_files/conf.py
Labels: ready

#138 FIX: Update displaymath for use with sphinxcontrib-jupyter:change_displaymath (A to C)
  rst_files/additive_functionals.rst
  rst_files/amss.rst
  rst_files/amss2.rst
  rst_files/arma.rst
  rst_files/calvo.rst
  rst_files/chang_credible.rst
  rst_files/chang_ramsey.rst
  rst_files/classical_filtering.rst
Labels: high-priority, in-work

#143 remove full stops from dyn_stack.rst
  rst_files/dyn_stack.rst
Labels: ready

#134 add inline highlighting to python_oop.rst
  rst_files/ifp.rst
  rst_files/optgrowth.rst
  rst_files/perm_income_cons.rst
  rst_files/python_by_example.rst
  rst_files/python_oop.rst
Labels: ready

#137 add mention of QE notes in getting_started.rst
  rst_files/getting_started.rst
Labels: ready

#151 add highlighting and other edits to arellano.rst
  rst_files/arellano.rst
Labels: ready

#149 remove empty input from lln_clt.rst
  rst_files/lln_clt.rst
Labels: ready

#141 edits to change_ramsey.rst
  rst_files/chang_ramsey.rst
Labels: ready

#68 update notation in mccall_model.rst
  rst_files/mccall_model.rst
Labels: ready

#60 remove error message in mle.rst
  rst_files/mle.rst
Labels: ready

#59 fix typo in scipy.rst
  rst_files/scipy.rst
Labels: ready

#58 edits to math in samuelson.rst
  rst_files/samuelson.rst
Labels: ready

#57 fix error in mccall_model.rst
  rst_files/mccall_model.rst
Labels: ready
