Repository QuantEcon/lecture-source-py, pull requests merged in 2019-08, with the labels that each got.

#542 Add PORT option for specify webserver and jupyter notebook ports
  Makefile
Labels: ready

#541 Update parallel option in Makefile to pass Integers
  Makefile
Labels: ready

#546 Fix broken links reported by link-checker
  source/rst/discrete_dp.rst
  source/rst/matplotlib.rst
  source/rst/pandas_panel.rst
  source/rst/scipy.rst
Labels: ready

#545 Remove notification for numba>=0.44.1
  source/rst/coleman_policy_iter.rst
  source/rst/optgrowth.rst
Labels: ready

#548 imports shifted on main lecture
  source/_static/lecture_specific/additive_functionals/amflss.py
  source/_static/lecture_specific/multiplicative_functionals/amflss_scalar.py
  source/rst/additive_functionals.rst
Labels: ready

#549 causing latex error while pdf conversion
  source/rst/markov_jump_lq.rst
  source/rst/tax_smoothing_2.rst
Labels: ready

#87 FIX: Table Formatting -- allow non-generic tables
  source/rst/harrison_kreps.rst
Labels: ready

#552 Shift imports
  source/rst/multiplicative_functionals.rst
Labels: ready

#556 multiplicative_functionals moved to sandpit
  source/rst/.DS_Store
  source/rst/multiplicative_functionals.rst
Labels: ready

#560 update gitignore
  .gitignore
Labels: ready

#557 logo required for pdfs
  .DS_Store
  source/.DS_Store
  source/_static/qe-logo-large.png
Labels: ready

#555 imports shifted from uncertainty_traps.py
  source/_static/lecture_specific/uncertainty_traps/uncertainty_traps.py
  source/rst/uncertainty_traps.rst
Labels: ready

#561 changes for multiplicative_functionals moved file to sandpit
  source/_static/lecture_specific/additive_functionals/amflss_scalar.py
  source/rst/additive_functionals.rst
  source/rst/arma.rst
  source/rst/index_time_series_models_grad.rst
Labels: ready

#562 ENH: Specify filenames
  Makefile
Labels: ready

#547 ENH: Theme variables
  conf.py
Labels: ready

#567 minimum imports needed for the .py files not to break
  source/_static/lecture_specific/additive_functionals/amflss.py
  source/_static/lecture_specific/additive_functionals/amflss_scalar.py
  source/_static/lecture_specific/uncertainty_traps/uncertainty_traps.py
Labels: ready

#569 code moved to lecture from external files
  source/_static/lecture_specific/additive_functionals/amflss.py
  source/_static/lecture_specific/additive_functionals/amflss_scalar.py
  source/rst/additive_functionals.rst
Labels: in-work

#573 code shifted to harrison_kreps
  source/_static/lecture_specific/harrison_kreps/hk_price_optimisticbeliefs.py
  source/_static/lecture_specific/harrison_kreps/hk_price_pessimisticbeliefs.py
  source/_static/lecture_specific/harrison_kreps/hk_price_singlebeliefs.py
  source/rst/harrison_kreps.rst
Labels: ready

#574 code shifted to lake_model.rst
  source/_static/lecture_specific/lake_model/lake_agent_dynamics.py
  source/_static/lecture_specific/lake_model/lake_fiscal_policy.py
  source/_static/lecture_specific/lake_model/lake_model.py
  source/_static/lecture_specific/lake_model/lake_rate_dynamics.py
  source/rst/lake_model.rst
Labels: ready

#572 these .py files are not used anywhere in lectures
  source/_static/lecture_specific/career/career.py
  source/_static/lecture_specific/dyn_stack/oligopoly.py
  source/_static/lecture_specific/egm_policy_iter/coleman_egm.py
  source/_static/lecture_specific/ifp/ifp.py
  source/_static/lecture_specific/jv/jv.py
  source/_static/lecture_specific/jv/jv_test.py
  source/_static/lecture_specific/linear_models/paths_and_hist.py
  source/_static/lecture_specific/linear_models/paths_and_stationarity.py
  source/_static/lecture_specific/linear_models/tsh_hg.py
Labels: ready

#571 code shifted to discrete_dp.rst
  source/_static/lecture_specific/discrete_dp/finite_dp_og_example.py
  source/_static/lecture_specific/discrete_dp/og_example_state_action.py
  source/rst/discrete_dp.rst
Labels: ready

#553 Update template with dropdown menubar
  theme/templates/lectures-local-css-js.tpl
  theme/templates/lectures-nbconvert.tpl
  theme/templates/lectures.tpl
Labels: ready

#585 code moved to python_essentials.rst
  source/_static/lecture_specific/python_essentials/us_cities.py
  source/rst/python_essentials.rst
Labels: ready

#587 code shifted to scipy.rst
  source/_static/lecture_specific/scipy/bisection.py
  source/rst/scipy.rst
Labels: ready

#586 code moved to robustness.rst
  source/_static/lecture_specific/robustness/robust_monopolist.py
  source/rst/robustness.rst
Labels: ready

#584 code shifted to pandas.rst
  source/rst/pandas.rst
Labels: ready

#583 code moved to lake_model.rst
  source/_static/lecture_specific/mccall/compute_reservation_wage.py
  source/_static/lecture_specific/mccall/mccall_bellman_iteration.py
  source/rst/lake_model.rst
Labels: ready

#582 code shifted to matsuyama.rst
  source/_static/lecture_specific/matsuyama/sim_time_series.py
  source/_static/lecture_specific/matsuyama/simulate_matsuyama.py
  source/rst/matsuyama.rst
Labels: ready

#581 code shifted to markov_perf.rst
  source/_static/lecture_specific/markov_perf/duopoly_mpe_dynamics.py
  source/rst/markov_perf.rst
Labels: ready

#579 shift_code_8
  source/_static/lecture_specific/lqramsey/lqramsey.py
  source/_static/lecture_specific/lqramsey/lqramsey_ar1.py
  source/_static/lecture_specific/lqramsey/lqramsey_discrete.py
  source/rst/lqramsey.rst
Labels: ready

#578 code shifted to lqcontrol.rst
  source/_static/lecture_specific/lqcontrol/lq_permanent_1.py
  source/rst/lqcontrol.rst
Labels: ready

#576 ENH: add pdf target in Makefile
  Makefile
Labels: ready

#577 FIX: Urlpath for images taking local reference in download notebooks
  Makefile
  conf.py
Labels: ready

#589 FIX: update lang_synonym to include ipython3
  conf.py
Labels: ready

#568 imports shifted for aiyagari.rst
  source/rst/aiyagari.rst
  source/rst/amss.rst
Labels: in-work, ready

#592 shift code to uncertainity_traps.rst
  source/_static/lecture_specific/uncertainty_traps/uncertainty_traps.py
  source/rst/uncertainty_traps.rst
Labels: ready

#591 code shifted to stationary_densities.rst
  source/_static/lecture_specific/stationary_densities/boxplot_example.py
  source/rst/stationary_densities.rst
Labels: ready

#590 code shifted to smoothing.rst
  source/_static/lecture_specific/smoothing/consumption_paths.py
  source/_static/lecture_specific/smoothing/lss_example.py
  source/_static/lecture_specific/smoothing/smoothing_actions.py
  source/_static/lecture_specific/smoothing/war_peace_example.py
  source/rst/smoothing.rst
Labels: ready

#593 Update book pdf filename in theme
  theme/templates/lectures-nbconvert.tpl
Labels: high-priority

#603 code moved towards PEP8 conventions for stationary_densities.rst
  source/rst/stationary_densities.rst
Labels: ready

#605 code moved towards pep8 conventions in scipy.rst
  source/rst/scipy.rst
Labels: ready

#604 code moved towards pep8 conventions for smoothing.rst
  source/rst/smoothing.rst
Labels: ready

#608 code moved towards pep8 conventions for tax_smoothing_1.rst
  source/rst/tax_smoothing_1.rst
Labels: ready

#606 code moved towards pep8 conventions in schelling.rst
  source/rst/schelling.rst
Labels: ready

#607 code moved towards pep8 conventions in tax_smoothing_3.rst
  source/rst/tax_smoothing_3.rst
Labels: ready

#613 code moved towards pep8 conventions for rational_expectations.rst
  source/rst/rational_expectations.rst
Labels: ready

#612 code moved towards pep8 conventions in rob_markov_perf.rst
  source/_static/lecture_specific/markov_perf/duopoly_mpe.py
  source/rst/rob_markov_perf.rst
Labels: ready

#611 code moved towards pep8 conventions in robustness.rst
  source/rst/robustness.rst
Labels: ready

#610 code moved to pep8 conventions for rosen_schooling_model
  source/rst/rosen_schooling_model.rst
Labels: ready

#609 code moved towards pep8 conventions in samuelson.rst
  source/rst/samuelson.rst
Labels: ready

#602 code moved towards pep_8 conventions for tax_smoothing_2
  source/rst/tax_smoothing_2.rst
Labels: ready

#544 FEAT: Add code execution testing through Travis CI
  .travis.yml
  Makefile
  scripts/travis-coverage.sh
Labels: ready

#616 unicode characters in getting_started.rst
  source/rst/getting_started.rst
Labels: ready
