Repository QuantEcon/lecture-source-py, pull requests merged in 2019-10, with the labels that each got.

#683 UPDATE: adjust structure for new python.quantecon.org bucket
  Makefile
  conf.py
  source/_static/lecture_specific/troubleshooting/launch.png
  source/rst/404.rst
  source/rst/about_lectures.rst
  source/rst/index.rst
  source/rst/index_postgrad.rst
  source/rst/index_toc.rst
  source/rst/search.rst
  source/rst/status.rst
  source/rst/troubleshooting.rst
  theme/html/404.html
  theme/html/about_lectures.html
  theme/html/search.html
  theme/html/status.html
  theme/static/css/basic.css
  theme/static/css/python.css
  theme/static/css/qe-menubar.css
  theme/static/css/qe.css
  theme/static/fonts/icons.eot
  theme/static/fonts/icons.svg
  theme/static/fonts/icons.ttf
  theme/static/fonts/icons.woff
  theme/static/fonts/selection.json
  theme/static/js/plugins.js
  theme/static/js/python.js
  theme/static/js/qe.js
  theme/templates/lectures-local-css-js.tpl
  theme/templates/lectures-nbconvert.tpl
  theme/templates/lectures.tpl
  theme/templates/python-html.tpl
Labels: ec2-migration

#690 Adjust README to use Jupinx
  README.md
Labels: ready

#694 Menubar separate py jl
  theme/templates/python-html.tpl
Labels: ready

#680 FEAT: Support for Individual PDF (requires sphinxcontrib-jupyter=0.5.0)
  .gitignore
  Makefile
  conf.py
  theme/templates/latex.tpl
Labels: ready

#699 math environment correction
  source/rst/smoothing.rst
Labels: ready

#700 FEAT: Styling and formatting of pdfs
  theme/templates/latex.tpl
Labels: ready

#704 fix python_index.html redirect issue that is no longer supported
  source/rst/additive_functionals.rst
  source/rst/aiyagari.rst
  source/rst/arma.rst
  source/rst/discrete_dp.rst
  source/rst/estspec.rst
  source/rst/finite_markov.rst
  source/rst/getting_started.rst
  source/rst/kalman.rst
  source/rst/lake_model.rst
  source/rst/linear_models.rst
  source/rst/lqcontrol.rst
  source/rst/markov_perf.rst
  source/rst/perm_income_cons.rst
  source/rst/rational_expectations.rst
  source/rst/robustness.rst
  source/rst/samuelson.rst
Labels: high-priority

#702 PDF: Enable unicode in verbatim blocks
  theme/templates/latex.tpl
Labels: ready
