Repository QuantEcon/lecture-source-py, pull requests merged in 2020-02, with the labels that each got.

#900 ols_update_links
  source/rst/ols.rst
Labels: ready

#894 stationary_densities_issue1
  source/_static/lecture_specific/stationary_densities/stochasticgrowth.py
Labels: in-work

#906 numba_issue
  source/rst/numba.rst
Labels: ready

#907 finite_markov_rephrasing
  source/rst/finite_markov.rst
Labels: ready

#891 additive_functions_issue1
  source/rst/additive_functionals.rst
Labels: in-work, ready

#895 classical_filtering_issue1
  source/rst/classical_filtering.rst
Labels: ready

#898 pandas_panel_issue1
  source/rst/pandas_panel.rst
Labels: ready

#896 lu_tricks_issue1
  source/rst/lu_tricks.rst
Labels: ready

#911 LNN_and_CLT_issue
  source/rst/lln_clt.rst
Labels: ready

#910 stationary_densities_fixed
  source/rst/stationary_densities.rst
Labels: ready

#919 writing_good_code_issue3
  source/rst/writing_good_code.rst
Labels: ready

#914 about_python_update_figure
  source/_static/lecture_specific/about_py/python_vs_matlab.png
  source/_static/lecture_specific/about_py/python_vs_rest.png
  source/rst/about_py.rst
Labels: ready

#922 writing_good_code_issue_4
  source/rst/writing_good_code.rst
Labels: ready

#890 pandas_issue6
  source/rst/pandas.rst
Labels: ready

#912 additive_functions_add_ref_and_boxes
  source/rst/additive_functionals.rst
Labels: ready

#913 finite_markov_ex_edit
  source/rst/finite_markov.rst
Labels: ready

#923 finishing up
  source/rst/getting_started.rst
Labels: in-work

#916 linear_model_issue3
  source/rst/linear_models.rst
Labels: ready

#930 functions_minor_edit
  source/rst/functions.rst
Labels: new lecture, ready

#934 about_py: excel link added and misc edits
  source/rst/about_py.rst
Labels: in-work

#935 Arellano code rewrite
  source/rst/arellano.rst
Labels: in-work

#939 optgrowth_issue
  source/rst/optgrowth.rst
Labels: ready
